services:
  - type: web
    name: ln-api
    env: docker
    rootDir: services/api
    dockerfilePath: services/api/Dockerfile
    plan: starter
    autoDeploy: true
    envVars:
      - key: DEV_STUB
        value: "true"
      - key: ML_URL
        value: https://ln-ml.onrender.com
      - key: MAX_WL_CYCLE_KG
        value: "3.0"
      - key: MIN_PROJECTED_BMI
        value: "18.5"
      - key: HBA1C_DROP_PER_CYCLE_HIGH
        value: "1.5"
      - key: HBA1C_DROP_PER_CYCLE_AMBER
        value: "1.0"
      - key: SUPABASE_URL
        value: ""
      - key: SUPABASE_API_KEY
        value: ""
      - key: DATABASE_URL
        fromDatabase:
          name: ln-db
          property: connectionString

  - type: web
    name: ln-ml
    env: docker
    rootDir: services/ml
    dockerfilePath: services/ml/Dockerfile
    plan: starter
    autoDeploy: true
    envVars:
      - key: GLY_MODEL
        value: ""
      - key: ANTH_MODEL
        value: ""
      - key: PREPROC
        value: ""

  # STATIC SITE (frontend)
  - type: static
    name: ln-web
    rootDir: apps/web
    buildCommand: npm ci && npm run build
    publishPath: dist
    envVars:
      - key: VITE_API_BASE
        value: https://ln-api-rgxr.onrender.com

databases:
  - name: ln-db
    plan: free
